version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: brivo_local_django
    container_name: django
    depends_on:
      - mailhog
    volumes:
      - .:/app:z
      - ./data:/vol/web/data:z
      - ./media:/vol/web/media:z
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    command: /start

  docs:
    image: brivo_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./brivo:/app/brivo:z
    ports:
      - "7000:7000"
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:5.0
    container_name: redis

  celeryworker:
    <<: *django
    image: brivo_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: brivo_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: brivo_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
