version: '3'

volumes:
  production_traefik: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: brivo_production_django
    depends_on:
      - redis
    env_file:
      - ./.envs/.production/.django
    command: /start

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: brivo_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    image: brivo_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: brivo_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: brivo_production_flower
    command: /start-flower

  
