# Generated by Django 3.0.12 on 2021-03-15 20:02

import brivo.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=brivo.users.models.user_profile_image_file_path)),
                ('general_units', models.CharField(choices=[('METRIC', 'Metric'), ('IMPERIAL', 'Imperial')], default='METRIC', max_length=255, verbose_name='General Units')),
                ('temperature_units', models.CharField(choices=[('CELSIUS', 'Celsius'), ('KELVIN', 'Kelvin'), ('FAHRENHEIT', 'Fahrenheit')], default='CELSIUS', max_length=255, verbose_name='Temperature Units')),
                ('gravity_units', models.CharField(choices=[('PLATO', 'Plato'), ('SG', 'SG')], default='Plato', max_length=255, verbose_name='Gravity Units')),
                ('color_units', models.CharField(choices=[('SRM', 'SRM'), ('EBC', 'EBC')], default='SRM', max_length=255, verbose_name='Color Units')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserBrewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=brivo.users.models.brewery_profile_image_file_path)),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brewery Name')),
                ('external_link', models.URLField(blank=True, null=True, verbose_name='External URL')),
                ('number_of_batches', models.IntegerField(default=0, verbose_name='Number of Batches')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brewery_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
