# Generated by Django 3.0.12 on 2021-02-16 22:09

import brivo.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=brivo.users.models.user_profile_image_file_path)),
                ('general_units', models.CharField(choices=[('METRIC', 'metric'), ('IMPERIAL', 'imperial')], max_length=255, verbose_name='General Units')),
                ('temperature_units', models.CharField(choices=[('CELSIUS', 'celsius'), ('KELVIN', 'kelvin'), ('FAHRENHEIT', 'fahrenheit')], max_length=255, verbose_name='Temperature Units')),
                ('gravity_units', models.CharField(choices=[('BLG', 'blg'), ('SG', 'sg')], max_length=255, verbose_name='Gravity Units')),
                ('color_units', models.CharField(choices=[('SRM', 'srm'), ('EBC', 'ebc')], max_length=255, verbose_name='Color Units')),
                ('ibu_type', models.CharField(choices=[('TINSETH', 'tinseth'), ('RAGER', 'rager')], max_length=255, verbose_name='IBU type')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='BreweryProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=brivo.users.models.brewery_profile_image_file_path)),
                ('name', models.CharField(max_length=50, verbose_name='Brewery Name')),
                ('external_link', models.URLField(verbose_name='External URL')),
                ('number_of_batches', models.IntegerField(verbose_name='Number of Batches')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
