# Generated by Django 3.0.12 on 2021-02-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210216_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='guma44', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
