# Generated by Django 3.0.12 on 2021-02-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210217_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breweryprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brewery_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color_units',
            field=models.CharField(choices=[('SRM', 'SRM'), ('EBC', 'EBC')], max_length=255, verbose_name='Color Units'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='general_units',
            field=models.CharField(choices=[('METRIC', 'Metric'), ('IMPERIAL', 'Imperial')], max_length=255, verbose_name='General Units'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gravity_units',
            field=models.CharField(choices=[('BLG', 'BLG'), ('SG', 'SG')], max_length=255, verbose_name='Gravity Units'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ibu_type',
            field=models.CharField(choices=[('TINSETH', 'Tinseth'), ('RAGER', 'Rager')], max_length=255, verbose_name='IBU type'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='temperature_units',
            field=models.CharField(choices=[('CELSIUS', 'Celsius'), ('KELVIN', 'Kelvin'), ('FAHRENHEIT', 'Fahrenheit')], max_length=255, verbose_name='Temperature Units'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
