# Generated by Django 3.0.12 on 2021-02-21 06:51

import brivo.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210217_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ibu_type',
        ),
        migrations.AlterField(
            model_name='breweryprofile',
            name='external_link',
            field=models.URLField(blank=True, verbose_name='External URL'),
        ),
        migrations.AlterField(
            model_name='breweryprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=brivo.users.models.brewery_profile_image_file_path),
        ),
        migrations.AlterField(
            model_name='breweryprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Brewery Name'),
        ),
        migrations.AlterField(
            model_name='breweryprofile',
            name='number_of_batches',
            field=models.IntegerField(default=0, verbose_name='Number of Batches'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color_units',
            field=models.CharField(choices=[('SRM', 'SRM'), ('EBC', 'EBC')], default='SRM', max_length=255, verbose_name='Color Units'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='general_units',
            field=models.CharField(choices=[('METRIC', 'Metric'), ('IMPERIAL', 'Imperial')], default='METRIC', max_length=255, verbose_name='General Units'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gravity_units',
            field=models.CharField(choices=[('PLATO', 'Plato'), ('SG', 'SG')], default='Plato', max_length=255, verbose_name='Gravity Units'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=brivo.users.models.user_profile_image_file_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='temperature_units',
            field=models.CharField(choices=[('CELSIUS', 'Celsius'), ('KELVIN', 'Kelvin'), ('FAHRENHEIT', 'Fahrenheit')], default='CELSIUS', max_length=255, verbose_name='Temperature Units'),
        ),
    ]
