# Generated by Django 3.0.12 on 2021-05-16 19:15

import brivo.brewery.fields
import brivo.utils.measures
from django.db import migrations, models
import django.db.models.deletion
import measurement.measures.mass
import measurement.measures.temperature
import measurement.measures.volume
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefermentable',
            name='color',
            field=brivo.brewery.fields.BeerColorField(measurement=brivo.utils.measures.BeerColor, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='beer_volume',
            field=brivo.brewery.fields.VolumeField(measurement=measurement.measures.volume.Volume, null=True, verbose_name='Beer Volume'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='boil_loss',
            field=brivo.brewery.fields.VolumeField(measurement=measurement.measures.volume.Volume, null=True, verbose_name='Boil Waists'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_gravity',
            field=brivo.brewery.fields.BeerGravityField(measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='End Gravity'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='grain_temperature',
            field=brivo.brewery.fields.TemperatureField(default=293.15, measurement=measurement.measures.temperature.Temperature, null=True, verbose_name='Grain Temperature'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='gravity_before_boil',
            field=brivo.brewery.fields.BeerGravityField(measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='Gravity Before Boil'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='initial_gravity',
            field=brivo.brewery.fields.BeerGravityField(measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='Initial Gravity'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='post_primary_gravity',
            field=brivo.brewery.fields.BeerGravityField(blank=True, measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='Post-primary Gravity'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='primary_fermentation_temperature',
            field=brivo.brewery.fields.TemperatureField(blank=True, measurement=measurement.measures.temperature.Temperature, null=True, verbose_name='Primary Fermentation Temperature'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='recipe',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, to='brewery.Recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='secondary_fermentation_temperature',
            field=brivo.brewery.fields.TemperatureField(blank=True, measurement=measurement.measures.temperature.Temperature, null=True, verbose_name='Secondary Fermentation Temperature'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='sparging_temperature',
            field=brivo.brewery.fields.TemperatureField(default=351.15, measurement=measurement.measures.temperature.Temperature, null=True, verbose_name='Sparging Temperature'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='wort_volume',
            field=brivo.brewery.fields.VolumeField(measurement=measurement.measures.volume.Volume, null=True, verbose_name='Wort Volume'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='extra',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='fermentable',
            name='country',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='hop',
            name='country',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brewery.Country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='ingredientextra',
            name='amount',
            field=brivo.brewery.fields.MassField(measurement=measurement.measures.mass.Mass, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='ingredientextra',
            name='recipe',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='brewery.Recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredientfermentable',
            name='amount',
            field=brivo.brewery.fields.MassField(help_text='Weight of the fermentable, extract or sugar.', measurement=measurement.measures.mass.Mass, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='ingredientfermentable',
            name='recipe',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fermentables', to='brewery.Recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredienthop',
            name='amount',
            field=brivo.brewery.fields.MassField(measurement=measurement.measures.mass.Mass, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='ingredienthop',
            name='recipe',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hops', to='brewery.Recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredientyeast',
            name='amount',
            field=brivo.brewery.fields.MassField(measurement=measurement.measures.mass.Mass, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='ingredientyeast',
            name='recipe',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeasts', to='brewery.Recipe', verbose_name='brewery.models.Recipe'),
        ),
        migrations.AlterField(
            model_name='inventoryextra',
            name='amount',
            field=brivo.brewery.fields.MassField(measurement=measurement.measures.mass.Mass, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='inventoryfermentable',
            name='amount',
            field=brivo.brewery.fields.MassField(measurement=measurement.measures.mass.Mass, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='inventoryhop',
            name='amount',
            field=brivo.brewery.fields.MassField(measurement=measurement.measures.mass.Mass, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='inventoryyeast',
            name='amount',
            field=brivo.brewery.fields.MassField(measurement=measurement.measures.mass.Mass, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='mashstep',
            name='recipe',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='mash_steps', to='brewery.Recipe', verbose_name='Recipe'),
        ),
        migrations.AlterField(
            model_name='mashstep',
            name='temperature',
            field=brivo.brewery.fields.TemperatureField(measurement=measurement.measures.temperature.Temperature, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='expected_beer_volume',
            field=brivo.brewery.fields.VolumeField(default=20, measurement=measurement.measures.volume.Volume, verbose_name='Expected Beer Volume'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='style',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.DO_NOTHING, to='brewery.Style', verbose_name='Style'),
        ),
        migrations.AlterField(
            model_name='style',
            name='color_max',
            field=brivo.brewery.fields.BeerColorField(blank=True, measurement=brivo.utils.measures.BeerColor, null=True, verbose_name='Color Max'),
        ),
        migrations.AlterField(
            model_name='style',
            name='color_min',
            field=brivo.brewery.fields.BeerColorField(blank=True, measurement=brivo.utils.measures.BeerColor, null=True, verbose_name='Color Min'),
        ),
        migrations.AlterField(
            model_name='style',
            name='fg_max',
            field=brivo.brewery.fields.BeerGravityField(blank=True, measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='FG Min'),
        ),
        migrations.AlterField(
            model_name='style',
            name='fg_min',
            field=brivo.brewery.fields.BeerGravityField(blank=True, measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='FG Max'),
        ),
        migrations.AlterField(
            model_name='style',
            name='og_max',
            field=brivo.brewery.fields.BeerGravityField(blank=True, measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='OG Min'),
        ),
        migrations.AlterField(
            model_name='style',
            name='og_min',
            field=brivo.brewery.fields.BeerGravityField(blank=True, measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='OG Max'),
        ),
        migrations.AlterField(
            model_name='style',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='brewery.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='temp_max',
            field=brivo.brewery.fields.TemperatureField(measurement=measurement.measures.temperature.Temperature, verbose_name='Max Temperature'),
        ),
        migrations.AlterField(
            model_name='yeast',
            name='temp_min',
            field=brivo.brewery.fields.TemperatureField(measurement=measurement.measures.temperature.Temperature, verbose_name='Min Temperature'),
        ),
    ]
