# Generated by Django 3.0.12 on 2021-07-07 04:59

import brivo.brewery.fields
from django.db import migrations, models
import measurement.measures.temperature


class Migration(migrations.Migration):

    dependencies = [
        ('brewery', '0004_fermentationcheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fermentationcheck',
            name='temperature',
        ),
        migrations.AddField(
            model_name='fermentationcheck',
            name='ambient_temperature',
            field=brivo.brewery.fields.TemperatureField(blank=True, measurement=measurement.measures.temperature.Temperature, null=True, verbose_name='Ambient Temperature'),
        ),
        migrations.AddField(
            model_name='fermentationcheck',
            name='beer_temperature',
            field=brivo.brewery.fields.TemperatureField(blank=True, measurement=measurement.measures.temperature.Temperature, null=True, verbose_name='Beer Temperature'),
        ),
        migrations.AddField(
            model_name='fermentationcheck',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment'),
        ),
    ]
