# Generated by Django 3.0.12 on 2021-03-12 15:48

import brivo.utils.measures
from django.db import migrations, models
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='beer_volume',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, null=True, verbose_name='Beer Volume'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='boil_waists',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Boil Waists'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='carbonation_level',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Carbonation Level'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='carbonation_type',
            field=models.CharField(choices=[('FORCED', 'forced'), ('REFERMENTATION', 'refermentation')], max_length=50, null=True, verbose_name='Carbonation Type'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='end_gravity',
            field=django_measurement.models.MeasurementField(measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='End Gravity'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='gravity_before_boil',
            field=django_measurement.models.MeasurementField(measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='Gravity Before Boil'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='initial_gravity',
            field=django_measurement.models.MeasurementField(measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='Initial Gravity'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='packaging_date',
            field=models.DateField(null=True, verbose_name='Packaging Start Day'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='post_primary_fermentation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Post-primary Gravity'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='primary_fermentation_start_day',
            field=models.DateField(null=True, verbose_name='Primary Fermentation Start Day'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='secondary_fermentation_start_day',
            field=models.DateField(null=True, verbose_name='Secondary Fermentation Start Day'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='wort_volume',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, null=True, verbose_name='Wort Volume'),
        ),
    ]
