# Generated by Django 3.0.12 on 2021-02-22 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brew', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='batch',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.Recipe', verbose_name='Recipe'),
        ),
        migrations.AddField(
            model_name='batch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='extras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.ExtraIngredient', verbose_name=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fermentables',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.FermentableIngredient', verbose_name=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='hops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.HopIngredient', verbose_name=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='yeasts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.YeastIngredient', verbose_name=''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.InventoryExtra', verbose_name='Extra'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_fermentable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.InventoryFermentable', verbose_name='Fermentable'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_hop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.InventoryHop', verbose_name='Hop'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='inventory_yeast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brew.InventoryYeast', verbose_name='Yeast'),
        ),
        migrations.AddField(
            model_name='hop',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brew.Country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='hop',
            name='substitute',
            field=models.ManyToManyField(blank=True, null=True, to='brew.Hop', verbose_name='Substitue'),
        ),
        migrations.AddField(
            model_name='fermentable',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brew.Country', verbose_name='Country'),
        ),
    ]
