# Generated by Django 3.0.12 on 2021-04-16 10:59

import brivo.utils.measures
from django.db import migrations, models
import django_measurement.models
import measurement.measures.volume


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='boil_loss',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.volume.Volume, null=True, verbose_name='Boil Waists'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='dry_hops_start_day',
            field=models.DateField(blank=True, null=True, verbose_name='Dry Hops Start Day'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='post_primary_gravity',
            field=django_measurement.models.MeasurementField(blank=True, measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='Post-primary Gravity'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='secondary_fermentation_start_day',
            field=models.DateField(blank=True, null=True, verbose_name='Secondary Fermentation Start Day'),
        ),
    ]
