# Generated by Django 3.0.12 on 2021-03-12 21:39

from django.db import migrations, models
import django_measurement.models
import measurement.measures.temperature


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0002_auto_20210312_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_number',
            field=models.IntegerField(null=True, verbose_name='Batch Number'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='brewing_day',
            field=models.DateField(null=True, verbose_name='Brewing Day'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='grain_temperature',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.temperature.Temperature, null=True, verbose_name='Grain Temperature'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='sparging_temperature',
            field=django_measurement.models.MeasurementField(measurement=measurement.measures.temperature.Temperature, null=True, verbose_name='Sparging Temperature'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='stage',
            field=models.CharField(choices=[('INIT', 'Init'), ('MASHING', 'Mashing'), ('BOIL', 'Boil'), ('PRIMARY FERMENTATION', 'Primary Fermentation'), ('SECONDARY FERMENTATION', 'Secondary Fermentation'), ('PACKAGING', 'Packaging'), ('FINISHED', 'Finished')], default='INIT', max_length=50, verbose_name='Stage'),
        ),
    ]
