# Generated by Django 3.0.12 on 2021-03-12 22:45

import brivo.utils.measures
from django.db import migrations, models
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0003_auto_20210312_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='post_primary_fermentation',
            field=django_measurement.models.MeasurementField(measurement=brivo.utils.measures.BeerGravity, null=True, verbose_name='Post-primary Gravity'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='stage',
            field=models.CharField(choices=[('INIT', 'Init'), ('MASHING', 'Mashing'), ('BOIL', 'Boil'), ('PRIMARY_FERMENTATION', 'Primary Fermentation'), ('SECONDARY_FERMENTATION', 'Secondary Fermentation'), ('PACKAGING', 'Packaging'), ('FINISHED', 'Finished')], default='INIT', max_length=50, verbose_name='Stage'),
        ),
    ]
