# Generated by Django 3.0.12 on 2021-03-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_auto_20210312_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='boil_waists',
            new_name='boil_loss',
        ),
        migrations.AddField(
            model_name='batch',
            name='dry_hops_start_day',
            field=models.DateField(null=True, verbose_name='Dry Hops Start Day'),
        ),
    ]
